service: aws-nodejs-sqs

provider:
  name: aws
  runtime: nodejs10.x
  tracing:
    apiGateway: true
    lambda: true
  iamRoleStatements:
    - Effect: "Allow" # xray permissions (required)
      Action:
       - xray:PutTraceSegments
       - xray:PutTelemetryRecords
       - sqs:ChangeMessageVisibility
       - sqs:DeleteMessage
       - sqs:ReceiveMessage
       - sqs:SendMessage
      Resource:
       - "*"

functions:
  insertSqs:
    handler: src/insert.handler
    events:
      - http:
          path: insertsqs
          method: post
  printSqs:
    handler: src/receive.handler
    events:
      - http:
          path: printsqs
          method: get